#!/bin/bash

set -ex

dartiq run "artiq_flash $FTDI_OPTION -d ./ --srcbuild -V build.netboot -t afck1v1 load"
sleep 5s
dartiq run "artiq_netboot -f ./build.netboot/software/runtime/runtime.bin -b $MCORD_DAQ_IP"
