#!/bin/bash
dartiq run "artiq_flash -I \"ftdi_location 1:3,1,3\" -d ./ --srcbuild -V build -t afck1v1 load"
sleep 5s
dartiq run "artiq_netboot -f ./build/software/runtime/runtime.bin -b 192.168.95.203"
