#!/bin/bash
dartiq run "artiq_flash -I \"ftdi_location 1:3,1,1\" -d ./ --srcbuild -V mcord_daq_fw -t afck1v1 load"
sleep 5s
dartiq run "artiq_netboot -f ./mcord_daq_fw/software/runtime/runtime.bin -b 192.168.95.203"
